Repository silverstripe/silverstripe-graphql, pull requests merged in 2018-10, with the labels that each got.

#184 FIX Incorrect parameter order of is_subclass_of
  src/Scaffolding/Scaffolders/DataObjectScaffolder.php
Labels: affects/v4, change/patch

#178 Middleware docs
  README.md
Labels: affects/v4, type/docs

#187 FIX Quote injector alias references, deprecated and removed support for in Symfony 4
  README.md
  _config/config.yml
Labels: affects/v4, change/patch

#180 API Increase visibility of private properties, used by ReadVersions in silverstripe/versioned
  src/Scaffolding/Traits/DataObjectTypeTrait.php
Labels: affects/v5, change/major
