Repository silverstripe/silverstripe-graphql, pull requests merged in 2019-01, with the labels that each got.

#200 BUG Ensure queries are sorted before limiting
  src/Pagination/Connection.php
Labels: affects/v4, change/patch

#155 Docs about JWT
  README.md
Labels: affects/v4, change/minor, effort/easy, impact/low, type/docs

#148 MINOR Switch logic in getDataObjectInstance to be slightly more readable
  src/Scaffolding/Traits/DataObjectTypeTrait.php
Labels: affects/v4, change/minor

#207 FIX Check readOne permissions against resolved DataObject
  src/Scaffolding/Scaffolders/CRUD/ReadOne.php
Labels: affects/v4, change/patch

#208 FIX Fall back to checking a singleton for canView() if no specific item exists
  src/Scaffolding/Scaffolders/CRUD/ReadOne.php
Labels: affects/v4, change/patch
